---
- name: Step 1 - Install required packages using dnf
  ansible.builtin.dnf:
    name:
      - make
      - ansible-core
      - git
    state: present
  become: true
  tags: download_tools

- name: Step 2 - Clone openstack-k8s-operators repository
  ansible.builtin.git:
    repo: https://github.com/openstack-k8s-operators/install_yamls.git
    dest: "{{ install_yamls_path }}"
  become_user: "{{ crc_user }}"
  tags: download_tools

- name: Step 3 - Download required tools
  shell: |
    cd {{ install_yamls_path }}/devsetup
    make download_tools
  become_user: "{{ crc_user }}"
  tags: download_tools

- name: Check if CRC is already deployed
  shell: |
    crc status
    # ? oc cluster-info
  become_user: "{{ crc_user }}"
  register: crc_initial_status
  ignore_errors: true
  tags: [check_crc, make_crc]

- name: Determine if CRC installation is needed
  set_fact:
    crc_needs_install: "{{ crc_initial_status.rc != 0 }}"
  tags: make_crc

- name: Step 4 - Install and start CRC using install_yamls
  shell: |
    cd {{ install_yamls_path }}/devsetup
    export PULL_SECRET={{ pull_secret_path }}
    export CPUS={{ crc_cpus }}
    export MEMORY={{ crc_memory }}
    export DISK={{ crc_disk }}
    make crc
  become_user: "{{ crc_user }}"
  register: make_crc_result
  timeout: "{{ crc_install_timeout }}"
  when: crc_needs_install | bool
  tags: make_crc

- name: Display make crc results
  debug:
    msg: "{{ make_crc_result.stdout }}"
  tags: make_crc

- name: Step 5 - Attach default interface to CRC
  shell: |
    cd {{ install_yamls_path }}/devsetup
    eval $(crc oc-env)
    oc login -u kubeadmin -p 12345678 https://api.crc.testing:6443
    make crc_attach_default_interface
  become_user: "{{ crc_user }}"
  register: make_crc_attach_result
  tags: make_crc_attach_interface

- name: Display Attach default interface results
  debug:
    msg: "{{ make_crc_attach_result.stdout }}"
  tags: make_crc_attach_interface

- name: Step 6 - Configure CRC storage
  shell: |
    cd {{ install_yamls_path }}
    eval "$(crc oc-env)"
    oc login -u kubeadmin -p 12345678 https://api.crc.testing:6443
    make crc_storage
  become_user: "{{ crc_user }}"
  register: make_crc_storage_result
  tags: make_crc_storage

- name: Display Configure CRC storage results
  debug:
    msg: "{{ make_crc_storage_result.stdout }}"
  tags: make_crc_storage

- name: Step 7 - Create input secrets
  shell: |
    cd {{ install_yamls_path }}
    eval "$(crc oc-env)"
    oc login -u kubeadmin -p 12345678 https://api.crc.testing:6443
    make input
  become_user: "{{ crc_user }}"
  register: make_input_result
  tags: make_input

- name: Display Create input secrets results
  debug:
    msg: "{{ make_input_result.stdout }}"
  tags: make_input